#!/bin/bash
# http://www.ducea.com/2007/11/22/xargs-unmatched-single-quote/
if [ $# -ge 2 ]
then
    find . -iname "*$2" -printf '"%p"\n' | xargs grep "$1" -sli
else
    find . -printf '"%p"\n' | xargs grep "$1" -sli
fi
